"""Render the browser-side expert-review annotation page."""

from __future__ import annotations

import hashlib
import json


def build_html(queue: list[dict[str, str]]) -> str:
    """Return a filterable, resumable HTML annotation page for ``queue``."""
    data = json.dumps(queue, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")
    queue_key = hashlib.sha256(
        "\n".join(row.get("osm_id", "") for row in queue).encode("utf-8")
    ).hexdigest()[:16]
    template = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Ireland geometry expert review</title>
<style>
:root{color-scheme:light;--ink:#17202a;--muted:#667085;--line:#d9dee5;--blue:#2563eb;--panel:#fff}
*{box-sizing:border-box}body{font:14px/1.4 system-ui,sans-serif;color:var(--ink);background:#f8fafc;margin:0}
main{max-width:1500px;margin:0 auto;padding:24px}h1{margin:0;font-size:24px}
.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}
.muted{color:var(--muted)}a{color:var(--blue)}button,input,select,textarea{font:inherit;border:1px solid #cfd5dd;border-radius:6px;background:var(--panel);padding:6px 8px}
button{cursor:pointer;font-weight:600}button:hover{border-color:var(--blue);color:var(--blue)}
.toolbar,.filters,.progress{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin:14px 0}
.toolbar{justify-content:space-between}.actions{display:flex;gap:8px}.filters{padding:12px;border:1px solid var(--line);border-radius:8px;background:var(--panel)}
.filters input{min-width:260px;flex:1}.filters select{min-width:170px}.progress{color:var(--muted);font-size:13px}.progress b{color:var(--ink)}
.table-wrap{overflow:auto;border:1px solid var(--line);border-radius:8px;background:var(--panel)}table{border-collapse:collapse;width:100%;min-width:1050px}
th,td{border-bottom:1px solid var(--line);padding:7px;vertical-align:top;text-align:left}th{background:#f4f6f8;position:sticky;top:0;z-index:1}tr:last-child td{border-bottom:0}
td input{width:100%;min-width:105px}td textarea{width:100%;min-width:210px;min-height:48px;resize:vertical}.candidate{min-width:180px}.evidence{min-width:290px}.label-cell{min-width:145px}.source-cell{min-width:260px}.detail{margin-top:8px;font-size:12px}.detail summary{cursor:pointer;color:var(--blue);font-weight:600}.detail-line{margin-top:4px}.detail-line b{color:var(--ink)}.source-links{overflow-wrap:anywhere}
.reviewed-at{display:block;color:var(--muted);font-size:11px;margin-top:4px;white-space:nowrap}.empty{padding:24px;color:var(--muted);text-align:center}
.target-row td{background:#eff6ff;box-shadow:inset 0 2px 0 #93c5fd,inset 0 -2px 0 #93c5fd}
.target-notice{margin:12px 0;padding:10px 12px;border:1px solid #f4c7c3;border-radius:8px;background:#fff7f6;color:#8f2d27}
@media(max-width:720px){main{padding:14px}.filters input{min-width:180px;width:100%}.toolbar{align-items:flex-start;flex-direction:column}}
</style></head>
<body><main><h1>Expert validation queue</h1><p class="muted">Labels are local review annotations, not automatic truth. Edits auto-save in this browser; download the CSV when ready, then rerun the review stage with it.</p>
<div class="toolbar"><div class="actions"><a href="report.html">← Dashboard</a><button id="download" type="button">Download labels CSV</button><button id="downloadJson" type="button">Download labels JSON</button><button id="importJsonButton" type="button">Import labels JSON</button><input id="importJson" type="file" accept=".json,application/json" aria-label="Import review labels JSON" hidden><button id="resetLocal" type="button">Clear saved edits</button></div><span id="saveStatus" class="muted" role="status" aria-live="polite"></span></div>
<div class="filters"><label class="sr-only" for="search">Search review queue</label><input id="search" type="search" placeholder="Search name, OSM ID, group, flags, or notes" aria-label="Search review queue"><label class="sr-only" for="statusFilter">Filter review state</label><select id="statusFilter" aria-label="Filter review state"><option value="all">All review states</option><option value="not_reviewed">Not reviewed</option><option value="supportive">Supportive</option><option value="ambiguous">Ambiguous</option><option value="not_supportive">Not supportive</option></select></div>
<div class="progress" aria-live="polite"><span id="count"></span><span>·</span><span id="progress"></span></div>
<div id="targetNotice" class="target-notice" role="status" hidden></div>
<div class="table-wrap"><table><caption class="sr-only">Expert review candidates</caption><thead><tr><th scope="col">#</th><th scope="col">Candidate</th><th scope="col">Evidence</th><th scope="col">Label</th><th scope="col">Confidence</th><th scope="col">Reviewer / source / notes</th></tr></thead><tbody id="rows"></tbody></table><div id="empty" class="empty" role="status" aria-live="polite" hidden>No candidates match this filter.</div></div></main>
<script>const DATA=__DATA__;const TARGET_ID=new URLSearchParams(location.search).get('osm_id')||'';const QUEUE_KEY='__QUEUE_KEY__';const BACKUP_SCHEMA='ireland-geometry-review-v1';const STORAGE_KEY=BACKUP_SCHEMA+':'+QUEUE_KEY;const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const choices=['supportive','ambiguous','not_supportive','not_reviewed'];const EDIT_FIELDS=['label','reviewer','reviewed_at','confidence','evidence_source','notes'];const $=id=>document.getElementById(id);
function saveable(row){return Object.fromEntries(EDIT_FIELDS.map(key=>[key,row[key]||'']));}
function touch(row){const active=row.label!=='not_reviewed'||row.reviewer||row.confidence||row.evidence_source||row.notes;row.reviewed_at=active?new Date().toISOString():'';}
function persist(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(DATA.map(row=>({osm_id:row.osm_id,...saveable(row)}))));$('saveStatus').textContent='Saved locally';}catch(error){$('saveStatus').textContent='Local save unavailable';}}
function restore(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');const byId=new Map(saved.map(row=>[row.osm_id,row]));DATA.forEach(row=>{const edit=byId.get(row.osm_id);if(edit)EDIT_FIELDS.forEach(key=>{if(edit[key]!==undefined)row[key]=edit[key];});});if(saved.length)$('saveStatus').textContent='Resumed saved edits';}catch(error){$('saveStatus').textContent='Could not resume saved edits';}}
function restoreViewState(){const params=new URLSearchParams(location.search);if(params.has('q'))$('search').value=params.get('q')||'';const state=params.get('status');if(choices.includes(state))$('statusFilter').value=state;}
function syncViewState(){const params=new URLSearchParams(location.search);const query=$('search').value.trim();if(query)params.set('q',query);else params.delete('q');const state=$('statusFilter').value;if(state&&state!=='all')params.set('status',state);else params.delete('status');const encoded=params.toString();history.replaceState(null,'',`${location.pathname}${encoded?`?${encoded}`:''}${location.hash}`);}
function matches(row){const query=$('search').value.trim().toLowerCase();const state=$('statusFilter').value;if(state!=='all'&&row.label!==state)return false;if(!query)return true;return [row.osm_id,row.name,row.group,row.flags,row.evidence_summary,row.notes,row.evidence_source,row.niah_name,row.reg_no,row.source_region,row.county,row.rating,row.niah_type,row.century,row.architect,row.architect_evidence,row.reference_sources,row.reference_types,row.reference_urls,row.archive_refs,row.evidence_text,row.validation_status,row.review_warnings,row.osm_heritage,row.wikidata].join(' ').toLowerCase().includes(query);}
function renderSummary(visible=DATA.filter(matches)){const counts=choices.reduce((out,key)=>(out[key]=DATA.filter(row=>row.label===key).length,out),{});$('count').textContent=`${visible.length} shown of ${DATA.length} candidates`;$('progress').innerHTML=`<b>${DATA.length-counts.not_reviewed}</b> reviewed · ${counts.supportive} supportive · ${counts.ambiguous} ambiguous · ${counts.not_supportive} not supportive`;}
function values(value){return String(value??'').split(/[|\\n]/).map(item=>item.trim()).filter(Boolean);}
function sourceLinks(value){return values(value).map(item=>(item.startsWith('https://')||item.startsWith('http://'))?`<a href="${esc(item)}" target="_blank" rel="noopener">${esc(item)}</a>`:`<span>${esc(item)}</span>`).join(' · ');}
function detailLine(label,value){return value?`<div class="detail-line"><b>${label}</b> ${esc(value)}</div>`:'';}
function evidenceDetails(r){const lines=[];const niah=[r.niah_name,r.reg_no,r.county,r.rating,r.century,r.niah_type].filter(Boolean).map(esc).join(' · ');if(niah)lines.push(`<div class="detail-line"><b>NIAH</b> ${niah}</div>`);if(r.architect)lines.push(detailLine('Architect',`${r.architect}${r.architect_confidence?` (${r.architect_confidence} confidence)`:''}`));if(r.architect_evidence)lines.push(detailLine('Architect evidence',r.architect_evidence));const refs=[r.reference_count&&`${r.reference_count} reference${r.reference_count==='1'?'':'s'}`,r.verified_reference_count&&`${r.verified_reference_count} verified`,r.independent_reference_count&&`${r.independent_reference_count} independent`].filter(Boolean);if(refs.length)lines.push(`<div class="detail-line"><b>References</b> ${refs.map(esc).join(' · ')}</div>`);if(r.reference_sources)lines.push(detailLine('Reference sources',r.reference_sources));if(r.reference_types)lines.push(detailLine('Reference types',r.reference_types));if(r.reference_urls)lines.push(`<div class="detail-line source-links"><b>Source links</b> ${sourceLinks(r.reference_urls)}</div>`);if(r.archive_refs)lines.push(detailLine('Archive refs',r.archive_refs));if(r.evidence_text)lines.push(detailLine('Evidence text',r.evidence_text));if(r.geometry_quality)lines.push(detailLine('Geometry',r.geometry_quality));if(r.match_mode)lines.push(detailLine('Match',`${r.match_mode}${r.dist_m?` · ${r.dist_m} m`:''}`));if(r.validation_status)lines.push(detailLine('Validation',r.validation_status));if(r.review_warnings)lines.push(detailLine('Warnings',r.review_warnings));if(r.osm_niah_ref)lines.push(detailLine('OSM–NIAH ref',r.osm_niah_ref));if(r.osm_heritage)lines.push(detailLine('OSM heritage',r.osm_heritage));if(r.wikidata)lines.push(detailLine('Wikidata',r.wikidata));if(r.image_paths)lines.push(detailLine('Images',r.image_paths));if(r.plan_paths)lines.push(detailLine('Plans',r.plan_paths));return lines.length?`<details class="detail"><summary>Evidence detail</summary>${lines.join('')}</details>`:'<span class="muted">No expanded dossier evidence.</span>';}
function render(){const visible=DATA.filter(matches);const targetMissing=Boolean(TARGET_ID&&!DATA.some(row=>row.osm_id===TARGET_ID));$('targetNotice').hidden=!targetMissing;$('targetNotice').textContent=targetMissing?`Target ${TARGET_ID} is not in the current ${DATA.length.toLocaleString()}-row review queue; this deep link came from a broader dashboard view. Use the dashboard or its OSM link to continue.`:'';$('rows').innerHTML=visible.map(r=>{const i=DATA.indexOf(r);const id=esc(r.osm_id);return `<tr class="${r.osm_id===TARGET_ID?'target-row':''}" data-osm-id="${id}"><td>${r.review_rank}</td><td class="candidate"><b>${esc(r.name||'Unnamed')}</b><br><span class="muted">${id} · score ${esc(r.score)}</span><br><a href="${esc(r.map_url)}" target="_blank" rel="noopener">Open map</a></td><td class="evidence">${esc(r.evidence_summary)}<br><span class="muted">${esc(r.flags)}</span>${evidenceDetails(r)}</td><td class="label-cell"><select data-i="${i}" data-edit="label" aria-label="Review label for ${id}">${choices.map(c=>`<option value="${c}" ${r.label===c?'selected':''}>${c}</option>`).join('')}</select><span class="reviewed-at">${r.reviewed_at?`edited ${esc(r.reviewed_at)}`:'not yet edited'}</span></td><td><input data-i="${i}" data-edit="confidence" aria-label="Confidence for ${id}" value="${esc(r.confidence)}" placeholder="0–1" inputmode="decimal"></td><td class="source-cell"><input data-i="${i}" data-edit="reviewer" aria-label="Reviewer for ${id}" value="${esc(r.reviewer)}" placeholder="reviewer"><input data-i="${i}" data-edit="evidence_source" aria-label="Evidence source for ${id}" value="${esc(r.evidence_source)}" placeholder="evidence source"><textarea data-i="${i}" data-edit="notes" aria-label="Review notes for ${id}" placeholder="evidence notes">${esc(r.notes)}</textarea></td></tr>`;}).join('');$('empty').hidden=visible.length>0;renderSummary(visible);bindEditors();if(TARGET_ID){document.querySelector('.target-row')?.scrollIntoView({block:'center'});}}
function bindEditors(){document.querySelectorAll('[data-edit]').forEach(element=>{const update=()=>{const row=DATA[Number(element.dataset.i)];row[element.dataset.edit]=element.value;touch(row);persist();const stamp=element.closest('td').querySelector('.reviewed-at');if(stamp)stamp.textContent=row.reviewed_at?`edited ${row.reviewed_at}`:'not yet edited';renderSummary();};element.addEventListener(element.tagName==='SELECT'?'change':'input',update);});}
function sync(){document.querySelectorAll('[data-edit]').forEach(element=>{DATA[Number(element.dataset.i)][element.dataset.edit]=element.value;});}
function downloadFile(name,content,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);}
function editableLabels(){sync();return DATA.map(r=>({osm_id:r.osm_id,...saveable(r)}));}
function download(){const labels=editableLabels();persist();const cols=['osm_id','label','reviewer','reviewed_at','confidence','evidence_source','notes'];const q=v=>`\"${String(v??'').replaceAll('\"','\"\"')}\"`;const csv=[cols.join(','),...labels.map(r=>cols.map(c=>q(r[c])).join(','))].join('\\n');downloadFile('expert-labels.csv',csv,'text/csv');$('saveStatus').textContent='CSV downloaded';}
function downloadJson(){const labels=editableLabels();const payload={schema:BACKUP_SCHEMA,queue_key:QUEUE_KEY,exported_at:new Date().toISOString(),editable_fields:EDIT_FIELDS,label_count:labels.length,labels};persist();downloadFile('expert-labels.json',JSON.stringify(payload,null,2),'application/json');$('saveStatus').textContent='JSON downloaded';}
async function importJson(event){const file=event.target.files?.[0];if(!file)return;try{const payload=JSON.parse(await file.text());const legacy=Array.isArray(payload);if(!legacy){if(!payload||typeof payload!=='object'||payload.schema!==BACKUP_SCHEMA)throw new Error('Unsupported JSON backup schema');if(payload.queue_key!==QUEUE_KEY)throw new Error('JSON backup belongs to a different review queue');}const labels=legacy?payload:payload.labels;if(!Array.isArray(labels))throw new Error('JSON must contain a labels array');const byId=new Map();let invalid=0;labels.forEach(row=>{if(!row||typeof row!=='object'||!row.osm_id){invalid+=1;return;}const id=String(row.osm_id);if(byId.has(id))throw new Error(`JSON contains duplicate label for ${id}`);byId.set(id,row);});if(invalid)throw new Error(`JSON contains ${invalid} invalid label records`);const currentIds=new Set(DATA.map(row=>row.osm_id));let imported=0;DATA.forEach(row=>{const edit=byId.get(row.osm_id);if(!edit)return;EDIT_FIELDS.forEach(key=>{if(Object.prototype.hasOwnProperty.call(edit,key))row[key]=String(edit[key]??'');});imported+=1;});const ignored=[...byId.keys()].filter(id=>!currentIds.has(id)).length;const suffix=ignored?'; ignored '+ignored+' outside current queue':'';persist();render();$('saveStatus').textContent='Imported '+imported+' labels'+suffix;}catch(error){$('saveStatus').textContent=`Could not import labels: ${error.message}`;}finally{event.target.value='';}}
 $('search').addEventListener('input',()=>{syncViewState();render();});$('statusFilter').addEventListener('change',()=>{syncViewState();render();});$('download').addEventListener('click',download);$('downloadJson').addEventListener('click',downloadJson);$('importJsonButton').addEventListener('click',()=>$('importJson').click());$('importJson').addEventListener('change',importJson);$('resetLocal').addEventListener('click',()=>{localStorage.removeItem(STORAGE_KEY);location.reload();});restore();restoreViewState();if(TARGET_ID)$('search').value=TARGET_ID;syncViewState();render();</script></body></html>"""
    return template.replace("__DATA__", data).replace("__QUEUE_KEY__", queue_key)
